### ISSUE TITLE
Spiel stürzt ab beim Abspeichern mit leerem String

### ISSUE THREAD

**Issue by gklasen** [Fausti/Tobor#1]
Siehe Titel :)

PS: Tolles Spiel!

**Comment by Fausti** [comment]
Ich habe die Issue Anzeige oben leider nicht bemerkt, das ist mir gerade echt peinlich^^

Fehler ist in 0.5.0 behoben :)

Danke für das Lob! Im Discord sind übrigens mittlerweile noch ein paar richtig tolle Episoden dazu gekommen, falls du noch nicht alle kennst: https://discord.gg/Er4Jmf95
